"""SC2 actor/data XML generator for converted models.

Produces ready-to-use XML snippets that can be pasted into the StarCraft 2 editor
or imported directly into a mod.
"""
from __future__ import annotations
from typing import Dict, List, Optional


def generate_actor_xml(model_name: str, m3_path: str,
                       texture_paths: Optional[List[str]] = None,
                       scale: float = 1.0,
                       animations: Optional[List[str]] = None,
                       team_color: bool = True) -> str:
    """Generate a CActorModel XML snippet for a converted model.

    Args:
        model_name: The SC2 unit name (e.g., 'Footman')
        m3_path: Asset path to the .m3 (e.g., 'Assets\\Units\\Human\\Footman\\Footman.m3')
        texture_paths: List of .dds asset paths
        scale: Actor scale multiplier
        animations: List of animation names to expose
        team_color: Whether to set up team color

    Returns a formatted XML string ready for the SC2 editor.
    """
    if animations is None:
        animations = ["Stand", "Walk", "Attack", "Spell", "Death", "Birth", "Portrait"]

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f'<!-- Auto-generated by wc3toSC2 v2.0 for model: {model_name} -->',
        f'<CActorModel id="{model_name}">',
        f'  <Model value="{m3_path}"/>',
        f'  <Scale value="{scale}"/>',
    ]

    # Animations
    lines.append('  <Animations>')
    for anim in animations:
        lines.append(f'    <Animation name="{anim}" variation="-1"/>')
    lines.append('  </Animations>')

    # Attachment points (required for SC2 hosting)
    lines.append('  <HostAttachments>')
    lines.append('    <HostAttachment ActorAttachment="Ref_Origin"/>')
    lines.append('    <HostAttachment ActorAttachment="Ref_Center"/>')
    lines.append('  </HostAttachments>')

    # Team color
    if team_color:
        lines.append('  <StatusBarFlags index="TeamColor" value="1"/>')

    # Textures (for reference)
    if texture_paths:
        lines.append('  <!-- Textures (import these into your mod): -->')
        for tp in texture_paths:
            lines.append(f'  <!--   {tp} -->')
        lines.append('  <TextureCount value="{0}"/>'.format(len(texture_paths)))

    lines.append('</CActorModel>')
    return "\n".join(lines)


def generate_unit_xml(model_name: str, actor_name: str,
                      hitpoints: int = 100, race: str = "Terran",
                      movement_speed: float = 2.25) -> str:
    """Generate a basic CUnit XML snippet.

    This is a minimal template — customize in the SC2 editor.
    """
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by wc3toSC2 v2.0 for unit: {model_name} -->
<CUnit id="{model_name}">
  <Name value="{model_name}"/>
  <Race value="{race}"/>
  <LifeStart value="{hitpoints}"/>
  <LifeMax value="{hitpoints}"/>
  <Speed value="{movement_speed}"/>
  <Actor value="{actor_name}"/>
</CUnit>"""


def generate_all(model_name: str, m3_asset_path: str,
                 scale: float = 1.0, texture_asset_paths: Optional[List[str]] = None,
                 animations: Optional[List[str]] = None, team_color: bool = True,
                 generate_unit: bool = False) -> Dict[str, str]:
    """Generate all SC2 XML snippets for a converted model.

    Returns a dict with keys 'actor' and optionally 'unit'.
    """
    result: Dict[str, str] = {}
    result["actor"] = generate_actor_xml(
        model_name, m3_asset_path, texture_asset_paths, scale, animations, team_color)
    if generate_unit:
        result["unit"] = generate_unit_xml(model_name, model_name)
    return result
