"""Pre-flight diagnostics engine: 15+ automated checks on MDX data before conversion.

Produces a structured report with issues, warnings, and auto-fixability status.
Also generates HTML and JSON report formats.
"""
from __future__ import annotations
from typing import Dict, List, Any, Optional, Tuple
import json, os


class DiagnosticIssue:
    """A single issue found during pre-flight analysis."""
    def __init__(self, code: str, severity: str, message: str,
                 auto_fixable: bool = False, detail: str = ""):
        self.code = code          # e.g. "ALPHA_INVERTED"
        self.severity = severity  # "error", "warning", "info"
        self.message = message
        self.auto_fixable = auto_fixable
        self.detail = detail

    def to_dict(self) -> Dict:
        return {
            "code": self.code, "severity": self.severity,
            "message": self.message, "auto_fixable": self.auto_fixable,
            "detail": self.detail,
        }


class DiagnosticReport:
    """Complete pre-flight diagnostic report."""
    def __init__(self, model_name: str = ""):
        self.model_name = model_name
        self.issues: List[DiagnosticIssue] = []
        self.stats: Dict[str, Any] = {}

    def add(self, code: str, severity: str, message: str,
            auto_fixable: bool = False, detail: str = ""):
        self.issues.append(DiagnosticIssue(code, severity, message, auto_fixable, detail))

    @property
    def errors(self) -> List[DiagnosticIssue]:
        return [i for i in self.issues if i.severity == "error"]

    @property
    def warnings(self) -> List[DiagnosticIssue]:
        return [i for i in self.issues if i.severity == "warning"]

    @property
    def info(self) -> List[DiagnosticIssue]:
        return [i for i in self.issues if i.severity == "info"]

    @property
    def auto_fixable_count(self) -> int:
        return sum(1 for i in self.issues if i.auto_fixable)

    @property
    def is_healthy(self) -> bool:
        return len(self.errors) == 0

    def to_dict(self) -> Dict:
        return {
            "model": self.model_name,
            "stats": self.stats,
            "issues": [i.to_dict() for i in self.issues],
            "summary": {
                "errors": len(self.errors),
                "warnings": len(self.warnings),
                "info": len(self.info),
                "auto_fixable": self.auto_fixable_count,
            },
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)

    def to_html(self) -> str:
        """Generate a self-contained HTML report."""
        issue_html = []
        for iss in self.issues:
            color = {"error": "#e74c3c", "warning": "#f39c12", "info": "#3498db"}.get(
                iss.severity, "#999")
            fix_badge = '<span style="background:#27ae60;color:#fff;padding:2px 6px;border-radius:3px;font-size:11px">auto-fix</span>' if iss.auto_fixable else ""
            issue_html.append(
                f'<tr><td style="color:{color};font-weight:bold">{iss.severity.upper()}</td>'
                f'<td><code>{iss.code}</code></td>'
                f'<td>{iss.message} {fix_badge}</td></tr>')

        return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Conversion Report: {self.model_name}</title>
<style>
body{{font-family:Segoe UI,Arial,sans-serif;background:#1e1e2e;color:#cdd6f4;margin:20px}}
h1{{color:#89b4fa}}h2{{color:#a6e3a1}}table{{border-collapse:collapse;width:100%}}
td,th{{padding:8px 12px;border-bottom:1px solid #313244;text-align:left}}
.summary{{display:flex;gap:20px;margin:15px 0}}
.stat{{background:#313244;padding:12px 20px;border-radius:8px;text-align:center}}
.stat .num{{font-size:28px;font-weight:bold}}
.stat .label{{font-size:12px;color:#a6adc8}}
.error{{color:#e74c3c}}.warning{{color:#f39c12}}.info{{color:#3498db}}
</style></head><body>
<h1>WC3 → SC2 Conversion Report</h1>
<h2>{self.model_name}</h2>
<div class="summary">
<div class="stat"><div class="num error">{len(self.errors)}</div><div class="label">Errors</div></div>
<div class="stat"><div class="num warning">{len(self.warnings)}</div><div class="label">Warnings</div></div>
<div class="stat"><div class="num info">{len(self.info)}</div><div class="label">Info</div></div>
<div class="stat"><div class="num" style="color:#27ae60">{self.auto_fixable_count}</div><div class="label">Auto-Fixable</div></div>
</div>
<h3>Issues</h3>
<table><tr><th>Severity</th><th>Code</th><th>Message</th></tr>
{''.join(issue_html) if issue_html else '<tr><td colspan="3" style="color:#a6e3a1">No issues found ✓</td></tr>'}
</table>
<p style="color:#6c7086;font-size:11px;margin-top:20px">Generated by wc3toSC2 v2.0</p>
</body></html>"""


def run_checks(mdx_data: Dict[str, Any], mdx_path: str = "",
               texture_search_dirs: Optional[List[str]] = None) -> DiagnosticReport:
    """Run all pre-flight diagnostic checks on parsed MDX data.

    Returns a DiagnosticReport with all issues found.
    """
    name = os.path.splitext(os.path.basename(mdx_path))[0] if mdx_path else "Model"
    report = DiagnosticReport(name)

    model = mdx_data.get("model", {})
    geosets = mdx_data.get("geosets", [])
    bones = mdx_data.get("bones", [])
    sequences = mdx_data.get("sequences", [])
    textures = mdx_data.get("textures", [])
    materials = mdx_data.get("materials", [])
    particles = mdx_data.get("particles", [])

    # --- Stats ---
    report.stats = {
        "version": model.get("version"),
        "geosets": len(geosets),
        "bones": len(bones),
        "sequences": len(sequences),
        "textures": len(textures),
        "materials": len(materials),
        "particles": len(particles),
        "total_vertices": sum(g.get("nverts", 0) for g in geosets),
        "total_triangles": sum(g.get("ntris", 0) for g in geosets),
        "bounds_radius": model.get("boundsRadius", 0),
    }

    # 1. Version check
    version = model.get("version", 0)
    if version != 800:
        report.add("VERSION", "warning",
                   f"MDX version is {version}, expected 800. May not convert correctly.",
                   detail=f"Only v800 (classic WC3) is fully supported.")

    # 2. Geoset checks
    if not geosets:
        report.add("NO_GEOSETS", "error", "Model has no geosets — nothing to convert.")
    for gi, g in enumerate(geosets):
        # Zero-area faces
        verts = g.get("verts", [])
        faces = g.get("faces", [])
        degenerate = 0
        for f in faces:
            if len(set(f)) < 3 or (len(f) == 3 and f[0] == f[1]):
                degenerate += 1
        if degenerate > 0:
            report.add("DEGENERATE_FACES", "warning",
                       f"Geoset[{gi}] has {degenerate} degenerate face(s)",
                       auto_fixable=True,
                       detail=f"{degenerate} faces have duplicate vertices and produce zero area.")
        # UV check
        uvs = g.get("uvs", [])
        if uvs:
            out_of_range = sum(1 for uv in uvs if uv[0] < -0.1 or uv[0] > 1.1 or uv[1] < -0.1 or uv[1] > 1.1)
            if out_of_range > len(uvs) * 0.3:
                report.add("UV_RANGE", "warning",
                           f"Geoset[{gi}] has {out_of_range}/{len(uvs)} UVs outside [0,1] — may tile incorrectly in SC2")
        # Material reference
        mat_id = g.get("materialId", -1)
        if mat_id < 0 or mat_id >= len(materials):
            report.add("BAD_MATERIAL_REF", "warning",
                       f"Geoset[{gi}] references material {mat_id} which doesn't exist. Using fallback.",
                       auto_fixable=True)

    # 3. Bone checks
    if not bones:
        report.add("NO_BONES", "warning", "Model has no bones — will export as static mesh.")
    else:
        roots = [b for b in bones if b.get("parentId") is None]
        if len(roots) == 0:
            report.add("NO_ROOT_BONE", "warning",
                       "No root bone found — a dummy root will be created.", auto_fixable=True)
        elif len(roots) > 1:
            report.add("MULTI_ROOT", "warning",
                       f"{len(roots)} root bones found — hierarchy may be split.")

        # Check for orphaned bones (no children, no vertices, no animation)
        bone_ids = {b["objectId"] for b in bones}
        parented = {b["parentId"] for b in bones if b.get("parentId") is not None}
        for b in bones:
            oid = b["objectId"]
            if oid not in parented and not b.get("tracks"):
                # Check if any geoset uses this bone
                used = False
                for g in geosets:
                    for vgroup in g.get("vertexBones", []):
                        if oid in vgroup:
                            used = True
                            break
                if not used:
                    report.add("ORPHANED_BONE", "info",
                               f"Bone '{b['name']}' has no children, vertices, or animations.")

    # 4. Sequence checks
    for s in sequences:
        duration = s.get("end", 0) - s.get("start", 0)
        if duration <= 0:
            report.add("ZERO_LENGTH_SEQ", "warning",
                       f"Sequence '{s['name']}' has zero or negative duration ({duration}ms)")
        if s.get("start", 0) > s.get("end", 0):
            report.add("SEQ_RANGE", "error",
                       f"Sequence '{s['name']}' has start > end ({s['start']} > {s['end']})")

    # 5. Texture checks
    for ti, t in enumerate(textures):
        if t.get("replaceableId", 0) in (1, 2):
            report.add("TEAM_COLOR", "info",
                       f"Texture[{ti}] is team color — will use SC2 TEAMEMIS emissive.")
        elif not t.get("path"):
            report.add("TEX_NO_PATH", "info",
                       f"Texture[{ti}] has no file path (may be a built-in reference).")

    # 6. Material checks
    for mi, mat in enumerate(materials):
        for li, layer in enumerate(mat.get("layers", [])):
            tid = layer.get("textureId", -1)
            if tid < 0 or tid >= len(textures):
                report.add("BAD_TEX_REF", "warning",
                           f"Material[{mi}] layer[{li}] references texture {tid} which doesn't exist.")
            if layer.get("filter") not in ("None", "Transparent", "Blend", "Additive",
                                            "AddAlpha", "Modulate", "Modulate2x"):
                report.add("UNKNOWN_FILTER", "info",
                           f"Material[{mi}] uses unknown filter mode: {layer.get('filter')}")

    # 7. Particle checks
    for ei, e in enumerate(particles):
        if e.get("emissionRate", 0) <= 0:
            report.add("ZERO_EMISSION", "warning",
                       f"Particle emitter '{e.get('name', ei)}' has zero emission rate — will be invisible.")
        lifespan = e.get("lifespan", 1.0)
        if lifespan < 0.01 or lifespan > 60:
            report.add("EXTREME_LIFESPAN", "warning",
                       f"Particle emitter '{e.get('name', ei)}' has extreme lifespan: {lifespan}s",
                       auto_fixable=True)

    return report
